env:
  env_name: Go2
  num_envs: 64
  max_episode_length: 1000
  reward_bias: 0.0
  control_steps: 1

  newton_env_cfg:
    obs_type: policy
    random_reset: false
    camera_tracking: false
    forward_reward_scale: 1.0
    upright_reward_scale: 0.05
    heading_reward_scale: 0.05
    alive_reward: 0.02
    yaw_rate_penalty_scale: 0.01
    termination_penalty: 1.0

rl:
  config:
    name: Go2PPO
    max_epochs: 200000
    horizon_length: 128
    normalize_input: true
    normalize_value: true
    reward_shaper:
      scale_value: 0.1
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    learning_rate: 0.0003
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 1000000
    save_best_after: 25
    save_frequency: 50
    torch_compile: false
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: true
    e_clip: 0.2
    minibatch_size: 2048
    mini_epochs: 4
    critic_coef: 2
    clip_value: false
    seq_length: 8
    bounds_loss_coef: 0.0

    player:
      deterministic: true
      games_num: 2
      num_actors: 1
      print_stats: true

  other_params:
    fixed_sigma: true
    sigma_init_val: 0.0

  network:
    mlp:
      units: [128, 256, 128]
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
